version: "2"
checks:
  argument-count:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50

plugins:
  csslint:
    enabled: false
    # Stylelint is used instead.
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
      - python
  eslint:
    enabled: true
    channel: "eslint-3"
    # config: .eslintrc.json
    # ignore: .eslintignore
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    # initial: .mdlrc
    # config: .mdlrc.style.rb
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineLength TooLong:
        enabled: false
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      PSR2 ControlStructures ControlStructureSpacing SpacingAfterOpenBrace:
        enabled: false
      PSR2 ControlStructures ControlStructureSpacing SpaceBeforeCloseBrace:
        enabled: false
      Squiz ControlStructures ForEachLoopDeclaration SpaceAfterOpen:
        enabled: false
      Squiz ControlStructures ForEachLoopDeclaration SpaceBeforeClose:
        enabled: false
      Squiz ControlStructures ForLoopDeclaration SpacingAfterOpen:
        enabled: false
      Squiz ControlStructures ForLoopDeclaration SpacingBeforeClose:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration BraceOnSameLine:
        enabled: false
  phpmd:
    enabled: true
    checks:
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
  shellcheck:
    enabled: true
  stylelint:
    enabled: true

exclude_patterns:
  - "_libs/**"
  - "**.min.css"
  - "**.custom.css"
  - "**.min.js"
  - "**.pack.js"
  - "**.custom.js"
