# eustasy/.Normal 4.0beta14
name: "Normal: SQL"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.sql"
      - ".github/workflows/sql.yml"
      - ".qlty/configs/.sqlfluff"
      - ".qlty/qlty.toml"
  pull_request:
    branches: [main]
    paths:
      - "**.sql"
      - ".github/workflows/sql.yml"
      - ".qlty/configs/.sqlfluff"
      - ".qlty/qlty.toml"

permissions:
  contents: read

jobs:
  sql:
    name: Lint + format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: eustasy/.normal/sql@v4
