# eustasy/.Normal 4.0beta10
name: "Normal: YAML"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.yml"
      - "**.yaml"
      - ".qlty/qlty.toml"
  pull_request:
    branches: [main]
    paths:
      - "**.yml"
      - "**.yaml"
      - ".qlty/qlty.toml"

permissions:
  contents: read

jobs:
  yaml:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: qltysh/qlty-action/install@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1

      - name: Lint (yamllint, actionlint, zizmor)
        run: qlty check --all --no-formatters --filter=yamllint,actionlint,zizmor
